### ISSUE TITLE
0. 在Chart Values文件中引用其它Values

### ISSUE THREAD

**Issue by nethibernate** [nethibernate/blog#18]
## 问题

Helm只会render template，不会render values；也就是说，helm对values file中的变量只会原封不动的使用，不会进行任何处理。

比如，values.yaml中定义了以下三个东西：
```
apiOneUrl: http://example.com/apiOne/v0
apiTwoUrl: http://example.com/apiTwo/v3
apiThreeUrl: http://example.com/apiThree/v7
```
正常情况下，会把url单独提取出来：
```
baseUrl: http://example.com
apiOneUrl: "{{ .Values.baseUrl }}/apiOne/v0"
apiTwoUrl: "{{ .Values.baseUrl }}/apiTwo/v3"
apiThreeUrl: "{{ .Values.baseUrl }}/apiThree/v7"
```
但是，在template中使用apiOneUrl时，无法得到计算后的结果，只会得到 ```{{ .Values.baseUrl }}/apiOne/v0```：
```
MyApiOneUrl: {{ .Values.apiOneUrl }}
```

## 解决方法：tpl function
tpl function是用来在template中将一个string作为template来进行计算的，这个function有两个参数：
* 第一个参数：等待计算的string
* 第二个参数：上下文context，一般就是 .（点）

将上面的改为如下：
```
MyApiOneUrl: {{ tpl .Values.apiOneUrl . }}
```
这样就会得到：
```
MyApiOneUrl: http://example.com/apiOne/v0
```

## 如何处理非string类型
如果是map或者list等非string类型怎么办？

比如，values.yaml中是如下格式：
```
apiUrls:
  apiOneUrl: "{{ .Values.baseUrl }}/apiOne/v0"
  apiTwoUrl: "{{ .Values.baseUrl }}/apiTwo/v3"
  apiThreeUrl: "{{ .Values.baseUrl }}/apiThree/v7"
```
此时再使用tpl：
```
MyApiUrls: {{ tpl .Values.apiUrls . }}
```
会得到报错：```wrong type for value; expected string; got map[string]interface {}```

**解决方法是通过toYaml，将非string类型转换成"YAML"格式的string类型，然后再使用tpl：**
```
MyApiUrls:
{{ tpl (.Values.apiUrls | toYaml) . | indent 2 }}
```
得到的结果：
```
MyApiUrls:
  apiOneUrl: http://example.com/apiOne/v0
  apiTwoUrl: http://example.com/apiTwo/v3
  apiThreeUrl: http://example.com/apiThree/v7
```
如果常用的话，可以提出一个 named template 方便调用：
```
{{ define "render-value" }}
  {{- if kindIs "string" .value }}
    {{- tpl .value .context }}
  {{- else }}
    {{- tpl (.value | toYaml) .context }}
  {{- end }}
{{- end }}
```
使用方式：
```
MyApiOneUrl: {{ include "render-value" ( dict "value" .Values.apiOneUrl "context" .) }}
MyApiUrls:
{{ include "render-value" ( dict "value" .Values.apiUrls "context" .) | indent 2}}
```

## 原始文章
文章地址： [Reference Other Values in Helm Chart Values File | by Jacky Jiang | ITNEXT](https://itnext.io/reference-other-values-in-helm-chart-values-file-19d44d9276c7)
